import { useState, useEffect, useCallback, type CSSProperties } from 'react';
import { PixelButton } from './PixelButton';

/** Media gallery — shows images/videos generated by MCP tools (mcp-image, etc.).
 *  Grid of thumbnails with metadata (prompt, model, agent, date). Filter by
 *  type and model. Click a thumbnail for a full-screen preview. */

interface MediaEntry {
  id: string;
  type: 'image' | 'video';
  path: string;
  prompt?: string;
  model?: string;
  agentId?: string;
  size: number;
  createdAt: number;
}

const headStyle: CSSProperties = {
  fontFamily: 'var(--cth-font-display)', fontSize: 8, lineHeight: '12px',
  color: 'var(--cth-ink-500)', textTransform: 'uppercase', marginBottom: 6
};

function fmtSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function fmtDate(ms: number): string {
  try { return new Date(ms).toLocaleDateString(); } catch { return '—'; }
}

export function MediaGallery() {
  const [media, setMedia] = useState<MediaEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState<'all' | 'image' | 'video'>('all');
  const [filterModel, setFilterModel] = useState<string>('all');
  const [preview, setPreview] = useState<MediaEntry | null>(null);

  const load = useCallback(async () => {
    try {
      const list = await window.cth.listMedia();
      setMedia(list ?? []);
    } catch { /* noop */ }
    setLoading(false);
  }, []);

  useEffect(() => { void load(); }, [load]);

  const models = Array.from(new Set(media.map((m) => m.model).filter(Boolean))) as string[];

  const filtered = media.filter((m) => {
    if (filterType !== 'all' && m.type !== filterType) return false;
    if (filterModel !== 'all' && m.model !== filterModel) return false;
    return true;
  });

  const removeMedia = async (id: string) => {
    try {
      await window.cth.deleteMedia(id);
      setMedia((prev) => prev.filter((m) => m.id !== id));
      setPreview(null);
    } catch { /* noop */ }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <div style={headStyle}>Media Gallery</div>
          <span style={{ fontSize: 12, color: 'var(--cth-ink-500)' }}>
            {loading ? 'Loading…' : `${filtered.length} items`}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {/* Type filter */}
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value as 'all' | 'image' | 'video')}
            style={{ fontSize: 11, padding: '2px 6px', background: 'var(--cth-cream-100)', border: '1px solid var(--cth-ink-300)' }}
          >
            <option value="all">All types</option>
            <option value="image">Images</option>
            <option value="video">Videos</option>
          </select>
          {/* Model filter */}
          {models.length > 0 && (
            <select
              value={filterModel}
              onChange={(e) => setFilterModel(e.target.value)}
              style={{ fontSize: 11, padding: '2px 6px', background: 'var(--cth-cream-100)', border: '1px solid var(--cth-ink-300)' }}
            >
              <option value="all">All models</option>
              {models.map((m) => <option key={m} value={m}>{m}</option>)}
            </select>
          )}
        </div>
      </div>

      {/* Grid */}
      {!loading && filtered.length === 0 && (
        <div style={{ padding: 16, fontSize: 12, color: 'var(--cth-ink-500)', textAlign: 'center' }}>
          No media yet. Generated images and videos from MCP tools will appear here.
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: 8 }}>
        {filtered.map((m) => (
          <div
            key={m.id}
            onClick={() => setPreview(m)}
            style={{
              cursor: 'pointer', position: 'relative',
              aspectRatio: '1', overflow: 'hidden',
              background: 'var(--cth-paper-100)',
              boxShadow: 'inset 0 0 0 1px var(--cth-ink-300)'
            }}
          >
            {m.type === 'image' ? (
              <img src={`file://${m.path}`} alt={m.prompt ?? ''} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '100%', height: '100%', fontSize: 24 }}>🎬</div>
            )}
            <span style={{
              position: 'absolute', bottom: 0, left: 0, right: 0,
              padding: '2px 4px', fontSize: 8,
              background: 'rgba(0,0,0,0.6)', color: 'white',
              overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap'
            }}>{m.model ?? m.type}</span>
          </div>
        ))}
      </div>

      {/* Full-screen preview */}
      {preview && (
        <div
          onClick={() => setPreview(null)}
          style={{
            position: 'fixed', inset: 0, zIndex: 9999,
            background: 'rgba(0,0,0,0.85)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            flexDirection: 'column', gap: 12, padding: 24, cursor: 'pointer'
          }}
        >
          {preview.type === 'image' ? (
            <img src={`file://${preview.path}`} alt={preview.prompt ?? ''} style={{ maxWidth: '80%', maxHeight: '70vh', objectFit: 'contain' }} />
          ) : (
            <video src={`file://${preview.path}`} controls style={{ maxWidth: '80%', maxHeight: '70vh' }} />
          )}
          <div style={{ color: 'white', fontSize: 12, textAlign: 'center', maxWidth: 600, cursor: 'default' }} onClick={(e) => e.stopPropagation()}>
            {preview.prompt && <div style={{ marginBottom: 4 }}>{preview.prompt}</div>}
            <div style={{ opacity: 0.7 }}>
              {preview.model && <span>{preview.model} · </span>}
              {fmtSize(preview.size)} · {fmtDate(preview.createdAt)}
            </div>
            <div style={{ marginTop: 8 }}>
              <PixelButton variant="secondary" size="sm" onClick={() => void removeMedia(preview.id)}>Delete</PixelButton>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
