import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, copyFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { app } from 'electron';

/** Media gallery: tracks every image/video generated by MCP tools (mcp-image,
 *  etc.) and exposes them to the renderer for a gallery view. */

export interface MediaEntry {
  id: string;
  type: 'image' | 'video';
  path: string;
  /** The prompt that generated this media (if known). */
  prompt?: string;
  /** The model used (if known). */
  model?: string;
  /** The agent id that generated this (if known). */
  agentId?: string;
  /** File size in bytes. */
  size: number;
  /** Creation time (epoch ms). */
  createdAt: number;
}

function mediaRoot(): string {
  const root = join(app.getPath('userData'), 'media');
  if (!existsSync(root)) { mkdirSync(join(root, 'images'), { recursive: true }); mkdirSync(join(root, 'videos'), { recursive: true }); }
  return root;
}

/** Scan the media directory and return all entries, newest-first. */
export function listMedia(): MediaEntry[] {
  const root = mediaRoot();
  const out: MediaEntry[] = [];
  for (const type of ['images', 'videos'] as const) {
    const dir = join(root, type);
    let files: string[] = [];
    try { files = readdirSync(dir); } catch { continue; }
    for (const f of files) {
      if (f.endsWith('.meta.json')) continue;
      const filePath = join(dir, f);
      try {
        const st = statSync(filePath);
        if (!st.isFile()) continue;
        const id = f.replace(/\.[^.]+$/, '');
        const metaPath = join(dir, `${id}.meta.json`);
        let meta: { prompt?: string; model?: string; agentId?: string } = {};
        try { if (existsSync(metaPath)) meta = JSON.parse(readFileSync(metaPath, 'utf8')); } catch { /* no meta */ }
        out.push({
          id, type: type === 'images' ? 'image' : 'video', path: filePath, size: st.size,
          createdAt: st.mtimeMs, ...meta,
        });
      } catch { /* skip unreadable */ }
    }
  }
  out.sort((a, b) => b.createdAt - a.createdAt);
  return out;
}

/** Capture a generated media file: copy it into the media directory with a
 *  metadata sidecar. Called from the PostToolUse hook on mcp__*__generate_image
 *  or similar. Returns the MediaEntry, or null on failure. */
export function captureMedia(sourcePath: string, opts: { prompt?: string; model?: string; agentId?: string; type?: 'image' | 'video' } = {}): MediaEntry | null {
  try {
    if (!existsSync(sourcePath)) return null;
    const type = opts.type ?? (sourcePath.match(/\.(mp4|webm|mov|avi)$/i) ? 'video' : 'image');
    const subdir = type === 'video' ? 'videos' : 'images';
    const dir = join(mediaRoot(), subdir);
    mkdirSync(dir, { recursive: true });
    // Generate a unique id from timestamp + random
    const id = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const ext = sourcePath.match(/(\.[^.]+)$/)?.[1] ?? (type === 'video' ? '.mp4' : '.png');
    const destPath = join(dir, `${id}${ext}`);
    copyFileSync(sourcePath, destPath);
    // Write metadata sidecar
    const meta: { prompt?: string; model?: string; agentId?: string } = {};
    if (opts.prompt) meta.prompt = opts.prompt;
    if (opts.model) meta.model = opts.model;
    if (opts.agentId) meta.agentId = opts.agentId;
    writeFileSync(join(dir, `${id}.meta.json`), JSON.stringify(meta));
    const st = statSync(destPath);
    return { id, type, path: destPath, size: st.size, createdAt: st.mtimeMs, ...meta };
  } catch { return null; }
}

/** Delete a media entry by id. Removes both the file and its metadata sidecar. */
export function deleteMedia(id: string): boolean {
  const root = mediaRoot();
  for (const subdir of ['images', 'videos']) {
    const dir = join(root, subdir);
    let files: string[] = [];
    try { files = readdirSync(dir); } catch { continue; }
    for (const f of files) {
      if (f.startsWith(`${id}.`)) {
        try {
          const filePath = join(dir, f);
          if (existsSync(filePath)) require('node:fs').unlinkSync(filePath);
        } catch { /* best-effort */ }
      }
    }
    // Check if we deleted anything
    try {
      const remaining = readdirSync(dir).filter((f) => f.startsWith(`${id}.`));
      if (remaining.length === 0) return true;
    } catch { /* */ }
  }
  return false;
}
